### PR TITLE
code structuring semantically done

### PR DESCRIPTION
**Pull request by Zayxoxo**
HTML structuring semantically organized.

The document is organized into three main sections: the header, main content area, and footer.

-- The <header> element contains a section with the class: "hurrdle_header" that is for the top part of the web page.

-- The <main> element holding the content of the page contains a section with the class: "hurrdle_main"  where the content features of the webpage will be structured.

-- The <footer> element includes a section with the class: "hurrdle_footer" which is reserved for the bottom part of the page.

### CODE REVIEW

**Comment by wisdombe** [comment]
Nice and Neat!

**Comment by wisdombe** [comment]
but it isn't complete yet, you didn't define the global styles in the CSS

**Review by Zayxoxo — COMMENTED** [review]
code structure updated.
css global attribute has been added.

**Review by Zayxoxo — COMMENTED** [review]
updated css structuring

**Comment by wisdombe** [comment]
Great work!

**Pull request merged**
